<?php use dawfony\Ti;?>
<?php global $URL_PATH ?>

<?php Ti::extend("templates\\MainView.phtml"); ?>
<?php Ti::startBlock("contenido"); ?>

<?php if ($title == "Listado"): ?>
<h1>Últimos posts:</h1>
<?php else: ?>
<h1>Posts de usuarios a los que sigues:</h1>
<?php endif; ?>
<br>
<?php

    if (count($posts) > 0) {
        foreach ($posts as $post) {
            ?>
            <div class="row border border-dark pt-1 pb-1">
                <div class="col-md-4"><img class="img-fluid" src="<?=$URL_PATH?>\\assets\\publicaciones\\<?=$post->foto?>"></div>
                <div class="col-md-5">
                    <h4><?=$post->resumen?></h4>
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="<?=$URL_PATH?>/post/<?=$post->id?>" class="btn btn-dark">Leer más</a>
                        </div>

                        <div class="col-sm-6">
                        likes: <span><?=$post->numero_likes?></span> - comentarios: <span><?=$post->numero_comentarios?></span>
                        </div>

                    </div>
                </div>
                <div class="col-md-3">
                    <h5>Por: <a href="<?=$URL_PATH?>/perfil/<?=$post->usuario_login?>"><?=$post->usuario_login?></a></h5>
                    <h6>en <?=$post->categoria?></h6>
                    <h5>el <?=$post->fecha?></h5>
                </div>
            </div>
            <br>
            <br>
            <?php
        }
    }

?>

<?php
    if (isset($_SESSION["login"])) {
    ?>
        <div style="position:fixed;bottom:60px;right:60px;">
            <div class="button btn-dark btn-lg">
                <a href="<?=$URL_PATH?>/subirpost" class="text-light">Subir Post</a>
            </div>
        </div>
    <?php
    }
?>


<?php Ti::endBlock(); ?>
<?php Ti::endExtend(); ?>