<?php use dawfony\Ti;?>
<?php global $URL_PATH ?>

<?php Ti::extend("templates\\MainView.phtml"); ?>
<?php Ti::startBlock("contenido"); ?>

<form action="<?=$URL_PATH?>/login" method="POST" class="bg-light pt-3 pl-5 pb-4">
    <div class="form-group row">
        <label for="login" class="col-sm-3 col-form-label">Login</label>
    <div class="col-sm-5">
        <input type="text" id="login" name="login" class="form-control" value="<?=$login?>">
        <span class="error"><?=$errorLoginVacio?></span>
    </div>
    </div>

    <div class="form-group row">
        <label for="password" class="col-sm-3 col-form-label">Contraseña</label>
    <div class="col-sm-5">
        <input type="password" id="password" name="password" class="form-control" required value="<?=$password?>">
        <span class="error"><?=$errorLog?></span>
    </div>
    </div>

<button type="submit" class=" mt-4 btn btn-success">Iniciar sesión</button>
<a class="btn btn-dark mt-4 ml-3" href="<?=$URL_PATH?>/login" role="button">Cancelar</a>


</form>

<?php Ti::endBlock(); ?>
<?php Ti::endExtend(); ?>