<?php use dawfony\Ti; ?>
<?php global $URL_PATH ?>

<?php Ti::extend("templates\\MainView.phtml"); ?>
<?php Ti::startBlock("contenido"); ?>

<div class="row">
    <div class="col-md-2">
        <img src="<?=$URL_PATH?>/assets/perfil.png" class="img-fluid">
    </div>

    <div class="col-md-10">
        <h2><?=$usuario->login?></h2>
        <h3><?=$usuario->nombre?></h3>
        Siguiendo <span class="badge badge-secondary"><?=$usuario->seguidos?></span> - Seguidores <span class="badge badge-secondary"><?=$usuario->seguidores?></span>
        <br><br>
        <?php if (!isset($_SESSION["login"])): ?>
            <div class="alert alert-dark" role="alert">
                Inicia sesión para seguir a <?=$usuario->login?> <br>
                <span class="small">¿No tienes cuenta? <a href="<?=$URL_PATH?>/registro">Regístrate</a></span>
            </div>
        <?php elseif ($_SESSION["login"] == $usuario->login): ?>
            <div class="alert alert-dark" role="alert">Este es tu perfil</div>
        <?php elseif ($usuario->loSigues): ?>
            <a class="btn btn-secondary text-light" href="<?=$URL_PATH?>/perfil/<?=$usuario->login?>/noseguir">Dejar de seguir a <?=$usuario->login?></a>
        <?php else: ?>
            <a class="btn btn-dark text-light" href="<?=$URL_PATH?>/perfil/<?=$usuario->login?>/seguir">Seguir a <?=$usuario->login?></a>
        <?php endif;?>
    </div>
</div>
<br>

<h3>Posts de <?=$usuario->login?></h3>
<table class="table">
<?php
    foreach ($posts as $post) {
        ?>
            <tr>
                <td class="col-md-8"><a href="<?=$URL_PATH?>/post/<?=$post->id?>" class="text-dark"><?=$post->resumen?></a></td>
                <td class="col-md-3"><?=$post->fecha?></td>
                <td class="col-md-1"><?=$post->categoria?></td>
            </tr>
        <?php
    }
?>
</table>
<?php Ti::endBlock(); ?>
<?php Ti::endExtend(); ?>